version: "3.9"
services:
  db:
    image: postgres:14
    container_name: career_vault_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: career_vault_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: career_vault_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
